### ISSUE TITLE
Bug in humidity compensation code for BME280

### ISSUE THREAD

**Issue by theraphim** [avaldebe/AQmon#1]
Greetings.

I see you tried to fix a bug in bme280_compensate_H_int32. Unfortunately, with your changes, the reported humidity is incorrect - for example, instead of 73%-ish it gives me 100. Restoring the original line (v1 = bit.rshift(v1 +16384,15)_bit.rshift(v2_H[2] + 8192,14)) fixes the problem.
Tested with 2 sensors I have here.

**Comment by avaldebe** [comment]
Thanks for the report,

It must be that my unit is out of calibration. Alas, my second sensor is still in the post...
In the meantime I restored the original line in 6276971.
Will come back to this when it arrives.

**Comment by avaldebe** [comment]
I got a second bme280 and with the original code this one reads ~0.4 of the observed relative humidity.
I suspect I'm reading one of the calibration parameters wrong. Will look further into it.

**Comment by avaldebe** [comment]
This issue is no longer relevant, but for the record I suspect that the problem was a numerical one, related to the integer kind in this version of nodemcu

**Comment by avaldebe** [comment]
This issue is no longer relevant. Current versions of nodemcu can be compiled with a native bme280 module.

The nodemcu/lua version of this project is no longer maintained.
Thr Arduino version of this project, on the V2 branch, is alive.
