### ISSUE TITLE
Error calling bme280

### ISSUE THREAD

**Issue by pr-boh** [avaldebe/AQmon#2]
Hi,
while trying your module bme280.lua, I get an error when calling "bme280.read":
The reason for trying your code is: Nodemcu firmware module mbe280 returns incorrect humitity, it is too low. Instead of about 40% it returns about 25%.
The same sensor installed on Raspi running bme280.py returns correct values at about 40% compared to other sensors. 
## I use your code for testing:

-- module setup and read
sda,scl=6,7 -- GPIO0,GPIO2                              --modified to 6,7
found=require('bme280').init(sda,scl)
print (found)                                                       -- modified
if found then
  bme280.read()                                                 -- getting error 
  pres,temp,rhum = bme280.pressure,bme280.temperature,bme280.humidity
end

-- release memory
bme280,package.loaded.bme280 = nil,nil

-- print formated results
print(('pres:%s hPa, temp:%s C, rhum:%s %%, heap:%d')
##  :format(f7p2(pres),f7p2(temp),f7p2(rhum),node.heap()))

Error is:
attempt to call field 'read' (a nil value)
stack traceback:
    bme280-setup.lua:6: in main chunk
    [C]: in function 'dofile'
    stdin:1: in main chunk

Init runs through, "found" returns the value 2.
Can you help me find out what's wrong?

**Comment by avaldebe** [comment]
Hi @pr-boh,

To me, it seems that the module is not loading correctly.
Can you try the following?

``` lua
require('bme280')
=type(bme280)
=bme280
=type(bme280.read)
=bme280.read
```

If any of the output is `nil` the module did not loaded correctly.

**Comment by pr-boh** [comment]
Hi avaldebe,
Thank you for your help!

I tried your suggestion on a clean (formatted) nodemcu with firmware from http://nodemcu-build.com/ . Only two modules are loaded: bme280.lua and setup.lua for testing (code see above).
I use esplorer.jar for loading and testing.

## FS Info:

bme280.lua      : 11625 bytes

## bme280_aqmon-setup.lua : 404 bytes

Total file(s)   : 2
Total size      : 12029 bytes

Total : 3351101 bytes
Used  : 12801 bytes
Remain: 3338300 bytes

> =node.info()
> 1   5   1   7054    1458400 4096    2   40000000
> =node.heap()
> 43272
> 
> This are the results:
> require('bme280')
> =type(bme280)
> romtable
> =bme280
> romtable: 0x402764a0
> =type(bme280.read)
> nil
> Do you have any idea?

**Comment by avaldebe** [comment]
Are you by any case using a `deb` build with a [native bme280 module](http://nodemcu.readthedocs.io/en/dev/en/modules/bme280)?
That would explain why `type(bme280)` returns `romtable` and why `type(bme280.read)` returns `nil`,
as `require` will load the native module before attempting to load `bme280.lc` and  `bme280.lua`.
If that is the case, you need to rename `bme280.lua` so `require` does not get confused...

**Comment by pr-boh** [comment]
Hi avaldebe,

thank you very much for your help. Renaming solved the problem!

**Comment by avaldebe** [comment]
Great! Closing the issue now. Just re-open it if you need more help.
